steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - compute
  - images
  - delete
  - $_MACHINE_NAME
- name: 'gcr.io/$PROJECT_ID/packer'
  args:
  - build
  - -var
  - project_id=$PROJECT_ID
  - -var
  - machine_name=$_MACHINE_NAME
  - gce_img.pkr.hcl
- name: 'ubuntu'
  entrypoint: 'env'
substitutions:
  _MACHINE_NAME: modified-ubuntu
